name: feature_record
description: "React Record Web App migrated to Flutter."
version: 0.0.1
homepage: ""
publish_to: "none"

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_globe_3d: ^2.2.5
  flutter_riverpod: ^3.2.1
  google_maps_flutter: ^2.5.3
  intl: ^0.20.2
  three_js: ^0.2.7
  vector_math: ^2.1.4
  core_ui:
    path: ../core_ui
  core_domain:
    path: ../core_domain
  core_data:
    path: ../core_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/record_globe_surface.frag
