import 'package:core_domain/core_domain.dart';

TravelAppState buildSeedTravelState() {
  return TravelAppState(
    trips: [
      TripSummary(
        id: 'trip-seoul-kyoto',
        title: 'Spring between Seoul and Kyoto',
        subtitle: 'Museums, rainy alleys, and late-night notes',
        startDate: DateTime(2025, 4, 14),
        endDate: DateTime(2025, 4, 22),
        heroPlace: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Kyoto',
          latitude: 35.0116,
          longitude: 135.7681,
        ),
        coverHint: 'Temple mornings and soft rain',
        memoryCount: 5,
        photoCount: 6,
        countryCount: 2,
      ),
      TripSummary(
        id: 'trip-paris-lisbon',
        title: 'Atlantic light in Lisbon',
        subtitle: 'A quieter week after Paris meetings',
        startDate: DateTime(2025, 9, 3),
        endDate: DateTime(2025, 9, 11),
        heroPlace: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        coverHint: 'Warm tram rides and tiled streets',
        memoryCount: 5,
        photoCount: 5,
        countryCount: 2,
      ),
      TripSummary(
        id: 'trip-busan-jeju',
        title: 'Coastline reset',
        subtitle: 'Short domestic escape with camera-first days',
        startDate: DateTime(2026, 1, 19),
        endDate: DateTime(2026, 1, 23),
        heroPlace: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Jeju',
          latitude: 33.4996,
          longitude: 126.5312,
        ),
        coverHint: 'Cold sea air, volcanic ridges',
        memoryCount: 4,
        photoCount: 7,
        countryCount: 1,
      ),
      TripSummary(
        id: 'trip-sapporo-osaka',
        title: 'Northern lights, city nights',
        subtitle: 'Sapporo snow mornings and Osaka food alleys',
        startDate: DateTime(2025, 12, 3),
        endDate: DateTime(2025, 12, 10),
        heroPlace: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Sapporo',
          latitude: 43.0618,
          longitude: 141.3545,
        ),
        coverHint: 'Cold air, ramen steam, neon nights',
        memoryCount: 5,
        photoCount: 8,
        countryCount: 1,
      ),
      TripSummary(
        id: 'trip-bangkok-chiangmai',
        title: 'Temple heat and overnight trains',
        subtitle:
            'Bangkok markets, Chiang Mai cafes, and one long sleeper ride',
        startDate: DateTime(2025, 6, 6),
        endDate: DateTime(2025, 6, 14),
        heroPlace: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Bangkok',
          latitude: 13.7563,
          longitude: 100.5018,
        ),
        coverHint: 'Lantern light and station echoes',
        memoryCount: 5,
        photoCount: 7,
        countryCount: 1,
      ),
      TripSummary(
        id: 'trip-sf-vancouver',
        title: 'Pacific edit sprint',
        subtitle: 'A coast-to-coast work trip that became a photo diary',
        startDate: DateTime(2025, 10, 1),
        endDate: DateTime(2025, 10, 9),
        heroPlace: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'San Francisco',
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        coverHint: 'Fog, seawall mornings, and laptop nights',
        memoryCount: 5,
        photoCount: 6,
        countryCount: 2,
      ),
      TripSummary(
        id: 'trip-barcelona-rome',
        title: 'Mediterranean transfer',
        subtitle: 'Two cities, one carry-on, and too many late dinners',
        startDate: DateTime(2026, 4, 18),
        endDate: DateTime(2026, 4, 26),
        heroPlace: const PlaceRef(
          countryCode: 'ES',
          countryName: 'Spain',
          cityName: 'Barcelona',
          latitude: 41.3874,
          longitude: 2.1686,
        ),
        coverHint: 'Balconies, blue water, and Roman stone',
        memoryCount: 4,
        photoCount: 6,
        countryCount: 2,
      ),
    ],
    entries: [
      JournalEntry(
        id: 'entry-1',
        tripId: 'trip-busan-jeju',
        title: 'First ferry morning',
        body:
            'Started the day with almost no plan and let the coastline decide the route.',
        recordedAt: DateTime(2026, 1, 20, 8, 12),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Jeju',
          latitude: 33.4996,
          longitude: 126.5312,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-2',
        tripId: 'trip-seoul-kyoto',
        title: 'Shrine path in the rain',
        body:
            'The path was almost empty. It felt like the whole city had gone quiet for an hour.',
        recordedAt: DateTime(2025, 4, 18, 17, 25),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Kyoto',
          latitude: 35.0116,
          longitude: 135.7681,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-3',
        tripId: 'trip-paris-lisbon',
        title: 'Blue hour tram window',
        body:
            'Caught the city as the lights came on. This is the one I want to remember later.',
        recordedAt: DateTime(2025, 9, 7, 19, 42),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-1'],
        hasPendingUpload: true,
      ),
      JournalEntry(
        id: 'entry-4',
        tripId: 'trip-seoul-kyoto',
        title: 'Quiet breakfast in Seoul',
        body:
            'Wrote route notes while the city was still slow. Good start before the airport rush.',
        recordedAt: DateTime(2025, 4, 14, 7, 50),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Seoul',
          latitude: 37.5665,
          longitude: 126.9780,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-5',
        tripId: 'trip-sapporo-osaka',
        title: 'Snow on the first platform',
        body:
            'Everything looked quieter than expected. The station air felt like a freezer and a calm start.',
        recordedAt: DateTime(2025, 12, 3, 8, 20),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Sapporo',
          latitude: 43.0618,
          longitude: 141.3545,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-2'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-6',
        tripId: 'trip-bangkok-chiangmai',
        title: 'Sleeper train notes',
        body:
            'Wrote route notes between stations and woke up just before sunrise outside Chiang Mai.',
        recordedAt: DateTime(2025, 6, 10, 6, 5),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Chiang Mai',
          latitude: 18.7883,
          longitude: 98.9853,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-7',
        tripId: 'trip-sf-vancouver',
        title: 'Fog line by the bridge',
        body:
            'The entire coast looked desaturated until the sun finally cut through after breakfast.',
        recordedAt: DateTime(2025, 10, 2, 9, 18),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'San Francisco',
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-3'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-8',
        tripId: 'trip-barcelona-rome',
        title: 'Blue hour on the last terrace',
        body:
            'Kept the phone down for once and just watched the rooftops switch from gold to purple.',
        recordedAt: DateTime(2026, 4, 24, 20, 11),
        place: const PlaceRef(
          countryCode: 'IT',
          countryName: 'Italy',
          cityName: 'Rome',
          latitude: 41.9028,
          longitude: 12.4964,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-4'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-9',
        tripId: 'trip-seoul-kyoto',
        title: 'Umeda arrival transfer',
        body:
            'Landed into Osaka first, dropped the bags, and started the Kansai leg before heading north.',
        recordedAt: DateTime(2025, 4, 15, 13, 10),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Osaka',
          latitude: 34.6937,
          longitude: 135.5023,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-5'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-10',
        tripId: 'trip-seoul-kyoto',
        title: 'First Kyoto alley loop',
        body:
            'Started early through Gion side streets before the crowds reached the shrines.',
        recordedAt: DateTime(2025, 4, 16, 9, 5),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Kyoto',
          latitude: 35.0116,
          longitude: 135.7681,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-11',
        tripId: 'trip-seoul-kyoto',
        title: 'Nara deer park detour',
        body:
            'Took the local train down for a slower afternoon and ended up staying until sunset.',
        recordedAt: DateTime(2025, 4, 17, 15, 30),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Nara',
          latitude: 34.6851,
          longitude: 135.8048,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-6'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-12',
        tripId: 'trip-seoul-kyoto',
        title: 'Last neon in Osaka',
        body:
            'Came back through Osaka for the final night and wrote the return route over late ramen.',
        recordedAt: DateTime(2025, 4, 20, 21, 10),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Osaka',
          latitude: 34.6937,
          longitude: 135.5023,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-13',
        tripId: 'trip-paris-lisbon',
        title: 'Paris departure platform',
        body:
            'Wrapped the meetings at dawn and left Paris with one notebook dedicated to Portugal.',
        recordedAt: DateTime(2025, 9, 3, 8, 30),
        place: const PlaceRef(
          countryCode: 'FR',
          countryName: 'France',
          cityName: 'Paris',
          latitude: 48.8566,
          longitude: 2.3522,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-14',
        tripId: 'trip-paris-lisbon',
        title: 'Alfama light cut',
        body:
            'The afternoon light bounced off the tile walls harder than expected and everything turned gold.',
        recordedAt: DateTime(2025, 9, 5, 18, 20),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-7'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-15',
        tripId: 'trip-paris-lisbon',
        title: 'Sintra morning mist',
        body:
            'Caught the first train and arrived before the fog fully lifted off the hills.',
        recordedAt: DateTime(2025, 9, 6, 10, 5),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Sintra',
          latitude: 38.8029,
          longitude: -9.3817,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-8'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-16',
        tripId: 'trip-paris-lisbon',
        title: 'Evora wall walk',
        body:
            'Took the inland route for one quiet historical stop before heading back to Lisbon.',
        recordedAt: DateTime(2025, 9, 8, 14, 40),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Evora',
          latitude: 38.5714,
          longitude: -7.9135,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-17',
        tripId: 'trip-busan-jeju',
        title: 'Busan harbor reset',
        body:
            'Started from the harbor with a smaller bag and a simple promise to stay near the coast.',
        recordedAt: DateTime(2026, 1, 19, 7, 20),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Busan',
          latitude: 35.1796,
          longitude: 129.0756,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-18',
        tripId: 'trip-busan-jeju',
        title: 'Seogwipo basalt trail',
        body:
            'The trail dropped straight into the surf line and the wind was colder than the forecast.',
        recordedAt: DateTime(2026, 1, 21, 16, 18),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Seogwipo',
          latitude: 33.2541,
          longitude: 126.5601,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-9'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-19',
        tripId: 'trip-busan-jeju',
        title: 'Hallasan ridge wind',
        body:
            'Clouds kept opening and closing over the ridge, making the whole climb feel edited in cuts.',
        recordedAt: DateTime(2026, 1, 22, 11, 12),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Hallasan',
          latitude: 33.3617,
          longitude: 126.5292,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-20',
        tripId: 'trip-sapporo-osaka',
        title: 'Otaru canal snow',
        body:
            'Took the short rail hop to Otaru and stayed out later than planned once the lamps came on.',
        recordedAt: DateTime(2025, 12, 4, 16, 10),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Otaru',
          latitude: 43.1907,
          longitude: 140.9947,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-10'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-21',
        tripId: 'trip-sapporo-osaka',
        title: 'Dotonbori after midnight',
        body:
            'The whole street felt louder after the Sapporo quiet, but it worked as a perfect reset.',
        recordedAt: DateTime(2025, 12, 7, 20, 50),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Osaka',
          latitude: 34.6937,
          longitude: 135.5023,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-22',
        tripId: 'trip-sapporo-osaka',
        title: 'Kyoto transfer morning',
        body:
            'Used the last morning to slow down in Kyoto before the return back south.',
        recordedAt: DateTime(2025, 12, 8, 9, 40),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Kyoto',
          latitude: 35.0116,
          longitude: 135.7681,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-23',
        tripId: 'trip-bangkok-chiangmai',
        title: 'Bangkok market heat',
        body:
            'Started too late, sweated through the market, and still stopped for one more bowl before leaving.',
        recordedAt: DateTime(2025, 6, 7, 13, 40),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Bangkok',
          latitude: 13.7563,
          longitude: 100.5018,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-11'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-24',
        tripId: 'trip-bangkok-chiangmai',
        title: 'Ayutthaya temple stop',
        body:
            'Broke the route north with one historical stop and a lot more sun than the station forecast promised.',
        recordedAt: DateTime(2025, 6, 8, 10, 30),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Ayutthaya',
          latitude: 14.3532,
          longitude: 100.5689,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-25',
        tripId: 'trip-bangkok-chiangmai',
        title: 'Lantern lane in Chiang Mai',
        body:
            'The old city felt slower than Bangkok immediately, and that shift made the whole trip click.',
        recordedAt: DateTime(2025, 6, 11, 19, 10),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Chiang Mai',
          latitude: 18.7883,
          longitude: 98.9853,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-12'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-26',
        tripId: 'trip-sf-vancouver',
        title: 'Portland rain edit',
        body:
            'Stopped long enough to edit the coastline set before moving the whole setup north again.',
        recordedAt: DateTime(2025, 10, 4, 12, 20),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'Portland',
          latitude: 45.5152,
          longitude: -122.6784,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-27',
        tripId: 'trip-sf-vancouver',
        title: 'Seattle ferry blue',
        body:
            'The harbor light finally turned bright enough that the entire day looked cleaner in-camera.',
        recordedAt: DateTime(2025, 10, 5, 17, 10),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'Seattle',
          latitude: 47.6061,
          longitude: -122.3328,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-13'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-28',
        tripId: 'trip-sf-vancouver',
        title: 'Vancouver seawall morning',
        body:
            'Closed the loop with a colder sunrise ride and one last coffee before check-out.',
        recordedAt: DateTime(2025, 10, 7, 8, 30),
        place: const PlaceRef(
          countryCode: 'CA',
          countryName: 'Canada',
          cityName: 'Vancouver',
          latitude: 49.2827,
          longitude: -123.1207,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-14'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-29',
        tripId: 'trip-barcelona-rome',
        title: 'Barcelona harbor start',
        body:
            'Started the transfer trip on the waterline and tried to keep the schedule loose for once.',
        recordedAt: DateTime(2026, 4, 19, 10, 15),
        place: const PlaceRef(
          countryCode: 'ES',
          countryName: 'Spain',
          cityName: 'Barcelona',
          latitude: 41.3874,
          longitude: 2.1686,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-15'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-30',
        tripId: 'trip-barcelona-rome',
        title: 'Nice platform transfer',
        body:
            'Used Nice as the long transfer stop and ended up walking the waterfront instead of resting.',
        recordedAt: DateTime(2026, 4, 21, 14, 0),
        place: const PlaceRef(
          countryCode: 'FR',
          countryName: 'France',
          cityName: 'Nice',
          latitude: 43.7102,
          longitude: 7.2620,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
    ],
    photos: [
      PhotoAsset(
        id: 'photo-1',
        fileName: 'lisbon-tram.heic',
        previewLabel: 'TRAM',
        format: 'HEIC',
        takenAt: DateTime(2025, 9, 7, 19, 40),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        uploadState: UploadState.queued,
      ),
      PhotoAsset(
        id: 'photo-2',
        fileName: 'sapporo-platform.heic',
        previewLabel: 'SNOW',
        format: 'HEIC',
        takenAt: DateTime(2025, 12, 3, 8, 18),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Sapporo',
          latitude: 43.0618,
          longitude: 141.3545,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-3',
        fileName: 'sf-fogline.heic',
        previewLabel: 'FOG',
        format: 'HEIC',
        takenAt: DateTime(2025, 10, 2, 9, 15),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'San Francisco',
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-4',
        fileName: 'rome-terrace.heic',
        previewLabel: 'ROME',
        format: 'HEIC',
        takenAt: DateTime(2026, 4, 24, 20, 8),
        place: const PlaceRef(
          countryCode: 'IT',
          countryName: 'Italy',
          cityName: 'Rome',
          latitude: 41.9028,
          longitude: 12.4964,
        ),
        uploadState: UploadState.queued,
      ),
      PhotoAsset(
        id: 'photo-5',
        fileName: 'osaka-transfer.heic',
        previewLabel: 'OSAKA',
        format: 'HEIC',
        takenAt: DateTime(2025, 4, 15, 13, 8),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Osaka',
          latitude: 34.6937,
          longitude: 135.5023,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-6',
        fileName: 'nara-park.heic',
        previewLabel: 'NARA',
        format: 'HEIC',
        takenAt: DateTime(2025, 4, 17, 15, 28),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Nara',
          latitude: 34.6851,
          longitude: 135.8048,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-7',
        fileName: 'alfama-gold.heic',
        previewLabel: 'ALFAMA',
        format: 'HEIC',
        takenAt: DateTime(2025, 9, 5, 18, 16),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-8',
        fileName: 'sintra-mist.heic',
        previewLabel: 'SINTRA',
        format: 'HEIC',
        takenAt: DateTime(2025, 9, 6, 10, 0),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Sintra',
          latitude: 38.8029,
          longitude: -9.3817,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-9',
        fileName: 'seogwipo-basalt.heic',
        previewLabel: 'SURF',
        format: 'HEIC',
        takenAt: DateTime(2026, 1, 21, 16, 14),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Seogwipo',
          latitude: 33.2541,
          longitude: 126.5601,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-10',
        fileName: 'otaru-canal.heic',
        previewLabel: 'OTARU',
        format: 'HEIC',
        takenAt: DateTime(2025, 12, 4, 16, 8),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Otaru',
          latitude: 43.1907,
          longitude: 140.9947,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-11',
        fileName: 'bangkok-market.heic',
        previewLabel: 'HEAT',
        format: 'HEIC',
        takenAt: DateTime(2025, 6, 7, 13, 36),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Bangkok',
          latitude: 13.7563,
          longitude: 100.5018,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-12',
        fileName: 'chiangmai-lantern.heic',
        previewLabel: 'LANTERN',
        format: 'HEIC',
        takenAt: DateTime(2025, 6, 11, 19, 8),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Chiang Mai',
          latitude: 18.7883,
          longitude: 98.9853,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-13',
        fileName: 'seattle-ferry.heic',
        previewLabel: 'FERRY',
        format: 'HEIC',
        takenAt: DateTime(2025, 10, 5, 17, 6),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'Seattle',
          latitude: 47.6061,
          longitude: -122.3328,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-14',
        fileName: 'vancouver-seawall.heic',
        previewLabel: 'SEAWALL',
        format: 'HEIC',
        takenAt: DateTime(2025, 10, 7, 8, 24),
        place: const PlaceRef(
          countryCode: 'CA',
          countryName: 'Canada',
          cityName: 'Vancouver',
          latitude: 49.2827,
          longitude: -123.1207,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-15',
        fileName: 'barcelona-harbor.heic',
        previewLabel: 'HARBOR',
        format: 'HEIC',
        takenAt: DateTime(2026, 4, 19, 10, 12),
        place: const PlaceRef(
          countryCode: 'ES',
          countryName: 'Spain',
          cityName: 'Barcelona',
          latitude: 41.3874,
          longitude: 2.1686,
        ),
        uploadState: UploadState.uploaded,
      ),
    ],
    syncSnapshot: SyncSnapshot(
      severity: SyncSeverity.pending,
      bannerTitle: '2 uploads waiting',
      bannerMessage:
          'Everything is saved locally. Upload will resume when the connection is stable.',
      pendingChanges: 3,
      pendingUploads: 2,
      lastSyncedAt: DateTime(2026, 3, 11, 19, 14),
    ),
  );
}
