import 'package:core_domain/core_domain.dart';

TravelAppState buildSeedTravelState() {
  return TravelAppState(
    trips: [
      TripSummary(
        id: 'trip-seoul-kyoto',
        title: 'Spring between Seoul and Kyoto',
        subtitle: 'Museums, rainy alleys, and late-night notes',
        startDate: DateTime(2025, 4, 14),
        endDate: DateTime(2025, 4, 22),
        heroPlace: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Kyoto',
          latitude: 35.0116,
          longitude: 135.7681,
        ),
        coverHint: 'Temple mornings and soft rain',
        memoryCount: 3,
        photoCount: 4,
        countryCount: 2,
      ),
      TripSummary(
        id: 'trip-paris-lisbon',
        title: 'Atlantic light in Lisbon',
        subtitle: 'A quieter week after Paris meetings',
        startDate: DateTime(2025, 9, 3),
        endDate: DateTime(2025, 9, 11),
        heroPlace: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        coverHint: 'Warm tram rides and tiled streets',
        memoryCount: 2,
        photoCount: 3,
        countryCount: 2,
      ),
      TripSummary(
        id: 'trip-busan-jeju',
        title: 'Coastline reset',
        subtitle: 'Short domestic escape with camera-first days',
        startDate: DateTime(2026, 1, 19),
        endDate: DateTime(2026, 1, 23),
        heroPlace: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Jeju',
          latitude: 33.4996,
          longitude: 126.5312,
        ),
        coverHint: 'Cold sea air, volcanic ridges',
        memoryCount: 2,
        photoCount: 6,
        countryCount: 1,
      ),
      TripSummary(
        id: 'trip-sapporo-osaka',
        title: 'Northern lights, city nights',
        subtitle: 'Sapporo snow mornings and Osaka food alleys',
        startDate: DateTime(2025, 12, 3),
        endDate: DateTime(2025, 12, 10),
        heroPlace: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Sapporo',
          latitude: 43.0618,
          longitude: 141.3545,
        ),
        coverHint: 'Cold air, ramen steam, neon nights',
        memoryCount: 4,
        photoCount: 8,
        countryCount: 1,
      ),
      TripSummary(
        id: 'trip-bangkok-chiangmai',
        title: 'Temple heat and overnight trains',
        subtitle:
            'Bangkok markets, Chiang Mai cafes, and one long sleeper ride',
        startDate: DateTime(2025, 6, 6),
        endDate: DateTime(2025, 6, 14),
        heroPlace: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Bangkok',
          latitude: 13.7563,
          longitude: 100.5018,
        ),
        coverHint: 'Lantern light and station echoes',
        memoryCount: 5,
        photoCount: 9,
        countryCount: 1,
      ),
      TripSummary(
        id: 'trip-sf-vancouver',
        title: 'Pacific edit sprint',
        subtitle: 'A coast-to-coast work trip that became a photo diary',
        startDate: DateTime(2025, 10, 1),
        endDate: DateTime(2025, 10, 9),
        heroPlace: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'San Francisco',
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        coverHint: 'Fog, seawall mornings, and laptop nights',
        memoryCount: 3,
        photoCount: 5,
        countryCount: 2,
      ),
      TripSummary(
        id: 'trip-barcelona-rome',
        title: 'Mediterranean transfer',
        subtitle: 'Two cities, one carry-on, and too many late dinners',
        startDate: DateTime(2026, 4, 18),
        endDate: DateTime(2026, 4, 26),
        heroPlace: const PlaceRef(
          countryCode: 'ES',
          countryName: 'Spain',
          cityName: 'Barcelona',
          latitude: 41.3874,
          longitude: 2.1686,
        ),
        coverHint: 'Balconies, blue water, and Roman stone',
        memoryCount: 2,
        photoCount: 7,
        countryCount: 2,
      ),
    ],
    entries: [
      JournalEntry(
        id: 'entry-1',
        tripId: 'trip-busan-jeju',
        title: 'First ferry morning',
        body:
            'Started the day with almost no plan and let the coastline decide the route.',
        recordedAt: DateTime(2026, 1, 20, 8, 12),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Jeju',
          latitude: 33.4996,
          longitude: 126.5312,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-2',
        tripId: 'trip-seoul-kyoto',
        title: 'Shrine path in the rain',
        body:
            'The path was almost empty. It felt like the whole city had gone quiet for an hour.',
        recordedAt: DateTime(2025, 4, 18, 17, 25),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Kyoto',
          latitude: 35.0116,
          longitude: 135.7681,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-3',
        tripId: 'trip-paris-lisbon',
        title: 'Blue hour tram window',
        body:
            'Caught the city as the lights came on. This is the one I want to remember later.',
        recordedAt: DateTime(2025, 9, 7, 19, 42),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-1'],
        hasPendingUpload: true,
      ),
      JournalEntry(
        id: 'entry-4',
        tripId: 'trip-seoul-kyoto',
        title: 'Quiet breakfast in Seoul',
        body:
            'Wrote route notes while the city was still slow. Good start before the airport rush.',
        recordedAt: DateTime(2025, 4, 14, 7, 50),
        place: const PlaceRef(
          countryCode: 'KR',
          countryName: 'South Korea',
          cityName: 'Seoul',
          latitude: 37.5665,
          longitude: 126.9780,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-5',
        tripId: 'trip-sapporo-osaka',
        title: 'Snow on the first platform',
        body:
            'Everything looked quieter than expected. The station air felt like a freezer and a calm start.',
        recordedAt: DateTime(2025, 12, 3, 8, 20),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Sapporo',
          latitude: 43.0618,
          longitude: 141.3545,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-2'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-6',
        tripId: 'trip-bangkok-chiangmai',
        title: 'Sleeper train notes',
        body:
            'Wrote route notes between stations and woke up just before sunrise outside Chiang Mai.',
        recordedAt: DateTime(2025, 6, 10, 6, 5),
        place: const PlaceRef(
          countryCode: 'TH',
          countryName: 'Thailand',
          cityName: 'Chiang Mai',
          latitude: 18.7883,
          longitude: 98.9853,
        ),
        type: MemoryType.note,
        photoAssetIds: const [],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-7',
        tripId: 'trip-sf-vancouver',
        title: 'Fog line by the bridge',
        body:
            'The entire coast looked desaturated until the sun finally cut through after breakfast.',
        recordedAt: DateTime(2025, 10, 2, 9, 18),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'San Francisco',
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-3'],
        hasPendingUpload: false,
      ),
      JournalEntry(
        id: 'entry-8',
        tripId: 'trip-barcelona-rome',
        title: 'Blue hour on the last terrace',
        body:
            'Kept the phone down for once and just watched the rooftops switch from gold to purple.',
        recordedAt: DateTime(2026, 4, 24, 20, 11),
        place: const PlaceRef(
          countryCode: 'IT',
          countryName: 'Italy',
          cityName: 'Rome',
          latitude: 41.9028,
          longitude: 12.4964,
        ),
        type: MemoryType.photo,
        photoAssetIds: const ['photo-4'],
        hasPendingUpload: false,
      ),
    ],
    photos: [
      PhotoAsset(
        id: 'photo-1',
        fileName: 'lisbon-tram.heic',
        previewLabel: 'TRAM',
        format: 'HEIC',
        takenAt: DateTime(2025, 9, 7, 19, 40),
        place: const PlaceRef(
          countryCode: 'PT',
          countryName: 'Portugal',
          cityName: 'Lisbon',
          latitude: 38.7223,
          longitude: -9.1393,
        ),
        uploadState: UploadState.queued,
      ),
      PhotoAsset(
        id: 'photo-2',
        fileName: 'sapporo-platform.heic',
        previewLabel: 'SNOW',
        format: 'HEIC',
        takenAt: DateTime(2025, 12, 3, 8, 18),
        place: const PlaceRef(
          countryCode: 'JP',
          countryName: 'Japan',
          cityName: 'Sapporo',
          latitude: 43.0618,
          longitude: 141.3545,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-3',
        fileName: 'sf-fogline.heic',
        previewLabel: 'FOG',
        format: 'HEIC',
        takenAt: DateTime(2025, 10, 2, 9, 15),
        place: const PlaceRef(
          countryCode: 'US',
          countryName: 'United States',
          cityName: 'San Francisco',
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        uploadState: UploadState.uploaded,
      ),
      PhotoAsset(
        id: 'photo-4',
        fileName: 'rome-terrace.heic',
        previewLabel: 'ROME',
        format: 'HEIC',
        takenAt: DateTime(2026, 4, 24, 20, 8),
        place: const PlaceRef(
          countryCode: 'IT',
          countryName: 'Italy',
          cityName: 'Rome',
          latitude: 41.9028,
          longitude: 12.4964,
        ),
        uploadState: UploadState.queued,
      ),
    ],
    syncSnapshot: SyncSnapshot(
      severity: SyncSeverity.pending,
      bannerTitle: '2 uploads waiting',
      bannerMessage:
          'Everything is saved locally. Upload will resume when the connection is stable.',
      pendingChanges: 3,
      pendingUploads: 2,
      lastSyncedAt: DateTime(2026, 3, 11, 19, 14),
    ),
  );
}
